### ISSUE TITLE
Unable to deploy in Cloud Function due to missing required package

### ISSUE THREAD

**Issue by jmlr-e-dialog** [google/argon#12]
I have been trying to redeploy for the last 3 days, without success. The Cloud Function Logs shows this:
 
```
Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'split2'
Require stack:
 - /workspace/argon.js
 - /workspace/index.js
 - /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js
 - /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/main.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/workspace/argon.js:19:15)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
Could not load the function, shutting down.
```

Is the first time I see this issue. I have successfully deploy Argon in the past. The source of the issue seems to be 'split2', imported in https://github.com/google/argon/blob/104181130a3f12a0de2bf5e82935d0419a847992/package.json#L28

**Comment by achembarpu** [comment]
Hi @jorgeloaiciga,
We are unable to reproduce this error. Could you try a fresh deployment, maybe using the GCP Cloud Shell?
Thanks!

**Comment by jmlr-e-dialog** [comment]
Hi @achembarpu, I managed to deploy using `gcloud`. It would seem like the confusion came from  misleading cloud function logs, the problem was actually that the wrong source directory was being pass in a Terraform deployment script. Thank you and sorry for the false bug.
